# This is a config for E2B sandbox template.
# You can use template ID (eh0860emqx28qyxmbctu) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("eh0860emqx28qyxmbctu") # Sync sandbox
# sandbox = await AsyncSandbox.create("eh0860emqx28qyxmbctu") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('eh0860emqx28qyxmbctu')

team_id = "af4eaf9c-3d40-415c-bb98-4831c47745cf"
memory_mb = 2_048
cpu_count = 4
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "eh0860emqx28qyxmbctu"
